name: CodeGraph
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10.11
  - hdbscan=0.8.30=py310h278f3c1_0
  - bertopic=0.15.0
  - pytorch>=1.10.0
  - torchaudio>=2.0.0
  - torchvision>=0.10.0
  - numba=0.57.1
  - pandas=1.5.3
  - numpy=1.23.5
  - pydantic=1.10.10
  - scikit-learn=1.2.0
  - fastapi=0.96.0
  - uvicorn=0.22.0
  - sqlalchemy=2.0.19
  - psycopg2=2.9.6